[package]
name = "arcstat"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcconfig = "0.2.0"
clap = { version = "4.4.11", features = ["cargo"]}
colored = "2.1.0"
regex = "1.8.2"
walkdir = "2"
